name: Contribution Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: raffaelramalhorosa
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output-tmp
          git rm -rf . --quiet
          cp dist/github-contribution-grid-snake.svg ./github-contribution-grid-snake.svg
          cp dist/github-contribution-grid-snake-dark.svg ./github-contribution-grid-snake-dark.svg
          git add github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg
          git commit -m "update snake"
          git push origin HEAD:output --force
